version: "3.8"
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: smartoee
      MYSQL_USER: smartoee
      MYSQL_PASSWORD: smartoee
    # ports:
    #   - "33061:3306" # chnage 33061
    cap_add:
      - SYS_NICE
    volumes:
      - ./data/mysql:/var/lib/mysql

  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: smartoee
      DB_PASS: smartoee
      DB_NAME: smartoee
      EMAIL_HOST: smtp4dev
      EMAIL_HAS_AUTH: 0
      EMAIL_USER: user
      EMAIL_PASSWORD: password
      EMAIL_PORT: 25
      EMAIL_USE_SSL: 0
      EMAIL_DEFAULT_FROM: hello@user.com
      LINE_API_URL: https://notify-api.line.me/api/notify
    ports:
      - "3020:3000"

  web:
    build:
      dockerfile: Dockerfile
      context: ./client
    restart: always
    ports:
      - "3010:80"

  poller:
    build:
      dockerfile: Dockerfile
      context: ./poller
    restart: always
    environment:
      SITE_ID: 1
      BASE_API_URL: http://api:3000
      READ_INTERVAL: "0/3 * * * * *"
      SYNC_INTERVAL: "0/3 * * * * *"
      NODE_TLS_REJECT_UNAUTHORIZED: 0
