services:
  poller:
    build:
      dockerfile: Dockerfile_standalone
      context: ./poller
    container_name: smartoee-poller-standalone
    restart: always
    environment:
      SITE_ID: 1
      BASE_API_URL: http://api:3000/api
      BASE_WS_URL: http://api:3000
      READ_INTERVAL: "0/3 * * * * *"
      SYNC_INTERVAL: "0/3 * * * * *"
      API_USER: poller@user.com
      API_PASS: P@ssword1
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      API_CONNECT_RETRY_DELAYL: 5000
      API_CONNECT_RETRY_COUNT: 10
      PLC_IP: '192.168.0.200'
    volumes:
      - ./poller-data:/app/data
