version: "3.8"
services:
  minio:
    image: "minio/minio"
    restart: always
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "P@ssword1"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./data/minio:/data"

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: smartoee
      MYSQL_USER: smartoee
      MYSQL_PASSWORD: smartoee
    ports:
      - "33061:3306"
    cap_add:
      - SYS_NICE
    volumes:
      - ./data/mysql:/var/lib/mysql

  api:
    image: node:16-alpine
    restart: always
    depends_on:
      - minio
      - db
    environment:
      STORAGE_URL: http://localhost:9000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: smartoee
      DB_PASS: smartoee
      DB_NAME: smartoee
      MINIO_END_POINT: minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: 0
      MINIO_LOCATION: us-east-1
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: "P@ssword1"
      EMAIL_HOST: smtp4dev
      EMAIL_PORT: 25
      EMAIL_USE_SSL: 0
      EMAIL_DEFAULT_FROM: hello@user.com
      LINE_API_URL: https://notify-api.line.me/api/notify
    ports:
      - "3020:3000"
    volumes:
      - ./api:/app
    working_dir: /app
    entrypoint:
      - npm
      - start

  web:
    image: nginx
    restart: always
    ports:
      - "3010:80"
    volumes:
      - ./client/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./client/build:/usr/share/nginx/html

  poller:
    image: node:16-alpine
    restart: always
    environment:
      SITE_ID: 1
      BASE_API_URL: http://api:3000
      READ_INTERVAL: "0/3 * * * * *"
      SYNC_INTERVAL: "0/3 * * * * *"
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    volumes:
      - ./poller:/app
    working_dir: /app
    entrypoint:
      - npm
      - start