export const SITE_ID = process.env.SITE_ID || '';
export const BASE_API_URL = process.env.BASE_API_URL || '';
export const BASE_WS_URL = process.env.BASE_WS_URL || '';
export const READ_INTERVAL = process.env.READ_INTERVAL || '0/3 * * * * *';
export const SYNC_INTERVAL = process.env.SYNC_INTERVAL || '0/10 * * * * *';
export const API_USER = process.env.API_USER || '';
export const API_PASS = process.env.API_PASS || '';
export const PLC_IP = (process.env.PLC_IP || '').split(',').filter((item) => item);
export const API_CONNECT_RETRY_DELAY = Number(process.env.API_CONNECT_RETRY_DELAY || '5000');
export const API_CONNECT_RETRY_COUNT = Number(process.env.API_CONNECT_RETRY_COUNT || '10');
